### ISSUE TITLE
Album-art for Google music wrong

### ISSUE THREAD

**Issue by mrMuppet** [UncleSamSwiss/ioBroker.squeezebox#3]
The link to the album-art of music played via Google-music all-inclusive is not fully working. You have to add the lms-server's url and even then it only links to one other cover in the playlist and not to the actual playing one.

**Comment by UncleSamSwiss** [comment]
Thanks for your report.
A few questions, I would like you to answer:
- Can you please provide a screenshot of how the URL looks like in ioBroker.admin.
- Can you please provide a log file with ioBroker.squeezebox running at the highest log level?
- Is there a way to test this without a Google Music account?
- Do the covers work with players? (software and/or hardware?)

**Comment by mrMuppet** [comment]
URL in ioBroker.admin is eg: googlemusicimage/lh4.ggpht.com/d-Gc0Bm_ZdK4WhqPx6NomGpBRAxfNQJB6pcf_ZU7itopeg4wFyDmidRI0AZx/image.jpg (i have to put the LMS-ip:port in front of it to use it.) ![screenshot1](https://cloud.githubusercontent.com/assets/2955497/14362804/72068922-fd01-11e5-84bf-4fc6e0795f65.GIF)

Logfile: http://pastebin.com/XzjPXqQD (IP & MAC anonymized)

I think you can test it with the free google-Play-Music account too. But you have to install the [code=https://github.com/hechtus/squeezebox-googlemusic]Google-Music plugin [/code]on your LMS. 

The Covers work on all Hardware-players and the Squeezectrl on android and the WebIF.

**Comment by UncleSamSwiss** [comment]
@mrMuppet Please have a look at my update and let me know if this fixes your issue.
Unfortunately I can't install this plug-in easily on my NAS (which is running LMS), so I can't test it.
